[package]
name = "{libname}"
description = "{description}"
version = "{version}"
authors = ["{author}"]
edition = "2018"
license = "{license}"

[dependencies]

[build-dependencies]
cc = "1.0"

[features]
default = ["{backend}"]
sequential_c = []
multicore_c = []
ispc = []
cuda = []
opencl = []
