[package]
name = "{libname}"
description = "{description}"
version = "{version}"
authors = ["{author}"]
edition = "2018"
license = "{license}"

[dependencies]

[build-dependencies]
bindgen = "0.51.0"
cc = "1.0"

[features]
default = ["sequential_c"]
sequential_c = []
cuda = []
opencl = []
